/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _HistoryRoute } from '../pages/history';
import { Route as _IndexRoute } from '../pages/';
import { Route as _ReactionRoute } from '../pages/reaction';
import { Route as _RecordRoute } from '../pages/record';
import { Route as _StatsRoute } from '../pages/stats';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/history': (typeof _HistoryRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/reaction': (typeof _ReactionRoute)['_inputType'];
    '/record': (typeof _RecordRoute)['_inputType'];
    '/stats': (typeof _StatsRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/history': (typeof _HistoryRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/reaction': (typeof _ReactionRoute)['_outputType'];
    '/record': (typeof _RecordRoute)['_outputType'];
    '/stats': (typeof _StatsRoute)['_outputType'];
  }
}
